export const mockProducts = [
  {
    id: "p1",
    name: "Premium Wheat (Grade A)",
    category: "Grains",
    price: 2450,
    unit: "per quintal",
    emoji: "🌾",
  },
  {
    id: "p2",
    name: "Basmati Rice",
    category: "Grains",
    price: 5200,
    unit: "per quintal",
    emoji: "🍚",
  },
  {
    id: "p3",
    name: "Mustard Oil (15L)",
    category: "Oil",
    price: 1850,
    unit: "per tin",
    emoji: "🛢️",
  },
  {
    id: "p4",
    name: "Urea Fertilizer",
    category: "Agro",
    price: 280,
    unit: "per bag",
    emoji: "🌱",
  },
  {
    id: "p5",
    name: "Cotton Fabric Roll",
    category: "Textile",
    price: 3200,
    unit: "per roll",
    emoji: "🧵",
  },
  {
    id: "p6",
    name: "Steel Utensils Set",
    category: "Household",
    price: 890,
    unit: "per set",
    emoji: "🍳",
  },
  {
    id: "p7",
    name: "Turmeric Powder",
    category: "Spices",
    price: 180,
    unit: "per kg",
    emoji: "🫚",
  },
  {
    id: "p8",
    name: "LED Bulb Pack (12W)",
    category: "Electronics",
    price: 450,
    unit: "per pack",
    emoji: "💡",
  },
];
